# -*- coding: utf-8 -*-
"""ProyectoFinal_SU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JS-nNGnpS6LGLSTps0GnLHZszm9NRl8s
"""

import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres.uyecvaskgaqtjymeswkp:1A*23456ssASñ@aws-0-ca-central-1.pooler.supabase.com:6543/postgres"
#"postgresql://postgres:1A*23456ssASñ@db.uyecvaskgaqtjymeswkp.supabase.co:6544/postgres"

# Ajuste david
engine = create_engine(DATABASE_URL)
df = pd.read_sql("select * from sabana_polizas_emasivos LIMIT 5", engine)
df.head()

