# -*- coding: utf-8 -*-
"""ProyectoFinal_SU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dt3ngwAzKIv4Z1BlyNsIW9xE1JtUIyo2

<a href="https://colab.research.google.com/github/andressanchez-gb/ProyectoFinal-SU/blob/Querys/ProyectoFinal_SU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres.uyecvaskgaqtjymeswkp:1A*23456ssASñ@aws-0-ca-central-1.pooler.supabase.com:6543/postgres"
#"postgresql://postgres:1A*23456ssASñ@db.uyecvaskgaqtjymeswkp.supabase.co:6544/postgres"

#Ajuste Andres
engine = create_engine(DATABASE_URL)
df = pd.read_sql("select * from sabana_polizas_emasivos LIMIT 5", engine)
df.head()

